# Generated by Django 6.0.5 on 2026-05-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="passengers",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
